#!/bin/bash
# Single-user /dev/X mounting | Spencer Tipping
# Licensed under the terms of the MIT source code license

cd_on '^/dev/(.*)' cd_dev_mount cd_dev_umount

function cd_dev_mount {
  cd_mount 'sudo mount' "$@"
}

function cd_dev_umount {
  cd_umount 'sudo umount' "$@"
}
