#!/bin/bash
# Auto EncFS mounting | Spencer Tipping
# Licensed under the terms of the MIT source code license

if which encfs > /dev/null; then
  cd_on '^enc:' cd_encfs_mount cd_encfs_umount
fi

function cd_encfs_wrapper {
  local target=${1#enc:}
  local mountpoint=$2

  # Convert the target into an absolute directory. Otherwise encfs will refuse
  # to run in daemon mode.
  pushd "$target" > /dev/null || return $?
  local real_target=$PWD
  popd > /dev/null
  encfs "$real_target" "$mountpoint"
}

function cd_encfs_mount {
  cd_mount cd_encfs_wrapper "$@"
}

function cd_encfs_umount {
  cd_umount "fusermount -u" "$@"
}
