#!/bin/bash
# Auto EncFS mounting | Spencer Tipping
# Licensed under the terms of the MIT source code license

if which encfs > /dev/null; then
  cd_on '^enc:'  cd_encfs_mount  cd_encfs_umount
  cd_on '^renc:' cd_rencfs_mount cd_rencfs_umount
else
  echo 'cd-encfs: no encfs binary found in $PATH'
fi

# An interesting thing with encfs: it doesn't by default hold an open
# filehandle to the directory you've mounted. As a result, if you cd into one
# virtual mountpoint, then cd into an enc:X directory inside that, the first
# one will be unmounted since it appears to not be in use.
#
# The workaround is to run a subshell process that will hold a reference (via
# CWD) to the outer filesystem for enough time to do the encFS mount. After
# that we can probably live with opportunistic unmounting provided no open
# files.

function cd_encfs_wrapper {
  local target=${1#enc:}
  local mountpoint=$2

  # Convert the target into an absolute directory. Otherwise encfs will refuse
  # to run in daemon mode.
  pushd "$target" > /dev/null || return $?
  local real_target=$PWD
  (sleep 60 &)
  popd > /dev/null
  encfs -o allow_root "$real_target" "$mountpoint"
}

function cd_encfs_mount {
  cd_mount cd_encfs_wrapper "$@"
}

function cd_encfs_umount {
  cd_umount "fusermount -u" "$@"
}

# encfs --reverse support
# Just like encfs, but backwards: you mount an unencrypted directory and see an
# encrypted one. Useful for rsync to insecure locations.
function cd_rencfs_wrapper {
  local target=${1#renc:}
  local mountpoint=$2

  # Convert the target into an absolute directory. Otherwise encfs will refuse
  # to run in daemon mode.
  pushd "$target" > /dev/null || return $?
  local real_target=$PWD
  (sleep 60 &)
  popd > /dev/null
  encfs --reverse -o allow_root "$real_target" "$mountpoint"
}

function cd_rencfs_mount {
  cd_mount cd_rencfs_wrapper "$@"
}

function cd_rencfs_umount {
  cd_umount "fusermount -u" "$@"
}
