#!/bin/bash
# Auto gitfuse mounting | Spencer Tipping
# Licensed under the terms of the MIT source code license

if which gitfuse > /dev/null; then
  cd_on '@git' cd_gitfuse_mount cd_gitfuse_umount
fi

function cd_gitfuse_wrapper {
  local target=$1
  local mountpoint=$2
  (gitfuse "${target/@git/}" "$mountpoint" 2>/dev/null &)
}

function cd_gitfuse_mount {
  cd_mount cd_gitfuse_wrapper "$@"
}

function cd_gitfuse_umount {
  cd_umount "fusermount -u" "$@"
}
