#!/bin/bash
# Auto yagfs mounting | Spencer Tipping
# Licensed under the terms of the MIT source code license

if which yagfs > /dev/null; then
  cd_on '^git:' cd_yagfs_mount cd_yagfs_umount
else
  echo 'cd-git: no yagfs binary found in $PATH'
fi

function cd_yagfs_wrapper {
  local target=$1
  local mountpoint=$2

  # The sleep here is to give yagfs a chance to warm up. Normally we don't need
  # to worry about this because most FUSE drivers exit once they're mounted,
  # but yagfs isn't that clever. If we don't sleep, then bash will complete the
  # cd into the not-yet-mounted directory and you'll have to 'cd .' in order to
  # see the mounted contents.
  (yagfs "${target#git:}" "$mountpoint" >& /dev/null || rmdir "$mountpoint" &)

  local count=0
  echo -n 'cd-git: awaiting git mount...'
  until [[ -d "$mountpoint/objects" || $count -gt 10 ]]; do
    sleep 0.25
    echo -n .
    if [[ ! -d "$mountpoint" ]]; then
      echo
      echo "cd-git: failed to mount $target"
      return 1
    fi
  done
  echo
}

function cd_yagfs_mount {
  cd_mount cd_yagfs_wrapper "$@"
}

function cd_yagfs_umount {
  cd_umount "fusermount -u" "$@"
}
