#!/bin/bash
# Auto yagfs mounting | Spencer Tipping
# Licensed under the terms of the MIT source code license

if which yagfs > /dev/null; then
  cd_on 'git:' cd_yagfs_mount cd_yagfs_umount
fi

function cd_yagfs_wrapper {
  local target=$1
  local mountpoint=$2
  (yagfs "${target#git:}" "$mountpoint" & sleep 0.25)
}

function cd_yagfs_mount {
  cd_mount cd_yagfs_wrapper "$@"
}

function cd_yagfs_umount {
  cd_umount "fusermount -u" "$@"
}
