#!/bin/bash
# cd history extension | Spencer Tipping
# Licensed under the terms of the MIT source code license

cd_on '^\^.+$'  cd_history_back_pattern
cd_on '^\^\d+$' cd_history_back_n
cd_on '^\^+$'   cd_history_back

function cd_history_back {
  local n=$((1 + ${#1}))
  cd_goto "${cd_history[-$n]}"
}

function cd_history_back_n {
  local n=$((1 + ${1#^}))
  cd_goto "${cd_history[-$n]}"
}

function cd_history_back_pattern {
  local pattern=${1#^}
  for ((i = ${#cd_history[@]} - 1; i >= 0; --i)); do
    if [[ "${cd_history[$i]}" =~ $pattern ]]; then
      cd_goto "${cd_history[$i]}"
      return $?
    fi
  done
  echo "cd: no history matching the regexp '$pattern'"
  return 1
}
