#!/bin/bash
# mkdir wrapper | Vivien Didelot and Spencer Tipping
# Licensed under the terms of the MIT source code license

# Keep a special file key in each directory we should nuke.
cd_autorm=$(basename $(mktemp -u "$HOME/.cd-autorm-XXXXXXXXXXXXXXXX"))

function cd_missing_fn {
  local target=$1
  mkdir -p "$target"
  touch "$target/$cd_autorm"

  echo "cd: created ephemeral directory $target"
  cd_goto "$target"
}

function cd_missing_unfn {
  # Look for the autorm key. This tells us that we created the directory, so we
  # have the ability to nuke it.
  local mode=$1
  local from=$2
  local to=$3
  if [[ -e "$from/$cd_autorm" ]]; then
    rm "$from/$cd_autorm"
    rmdir "$from" && echo "cd: removed ephemeral directory $from"
  fi
}
