#!/bin/bash
# mkdir wrapper | Vivien Didelot and Spencer Tipping
# Licensed under the terms of the MIT source code license

# Keep a special file key in each directory we should nuke. The key has enough
# entropy that nobody would create such a file by mistake.
cd_autorm=.cd-autorm-$(git hash-object <(echo $RANDOM $RANDOM $RANDOM $RANDOM \
                                              $RANDOM $RANDOM $RANDOM $RANDOM))
function cd_missing_fn {
  local target=$1
  mkdir -p "$target"
  touch "$target/$cd_autorm"
  cd_goto "$target"
}

function cd_missing_unfn {
  # Look for the autorm key. This tells us that we created the directory, so we
  # have the ability to nuke it.
  local mode=$1
  local from=$2
  local to=$3
  if [[ -f "$from/$cd_autorm" ]]; then
    rm "$from/$cd_autorm"
    lsof +D "$from" > /dev/null || rmdir --ignore-fail-on-non-empty "$from"
  fi
}
