#!/bin/bash
# Auto SSHFS mounting | Spencer Tipping
# Licensed under the terms of the MIT source code license

if which sshfs > /dev/null; then
  cd_on '^([^:]+):.*' cd_sshfs_mount cd_sshfs_umount
else
  echo 'cd-ssh: no sshfs binary found in $PATH'
fi

function cd_sshfs_mount {
  cd_mount "sshfs -o follow_symlinks,allow_root" "$@"
}

function cd_sshfs_umount {
  cd_umount "fusermount -u" "$@"
}
