#!/bin/bash
# Ancestor/descendant traversal | Spencer Tipping
# Licensed under the terms of the MIT source code license

cd_on '^\.\.[^/]' cd_traverse_ancestor
cd_on '^\*\*'     cd_traverse_descendant

function cd_traverse_ancestor {
  local pattern="${1#..}[^/]*$"
  local firstpwd=$PWD
  while [[ !("${PWD##*/}" =~ $pattern) && $PWD != / ]]; do
    builtin cd ..
  done
  local newpwd=$PWD
  builtin cd "$firstpwd"    # go back so we can set $OLDPWD correctly
  cd_goto "$newpwd"         # adds an entry to history, which we probably want
}

function cd_traverse_descendant {
  local destination=./**/${1#\*\*}
  cd_goto $destination
}
